apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
data:
  index.html: |

    <!DOCTYPE html>
    <html>
    <head>
    <title>Desafio k8s - nginx</title>
    </head>
    <body>

    <p>Code.education Rocks!</p>

    </body>
    </html>